// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppConfig = { last_folder: string | null, last_theme: number | null, guide_volume: number | null, fullscreen: boolean | null, dark_mode: boolean | null, mic_active: boolean | null, preferred_mic: string | null, whisper_model: string | null, beam_size: number | null, batch_size: number | null, last_video_flavor: number | null, separator: string | null, language_overrides: { [key in string]: string } | null, };
