// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MicSlotSetting } from "./MicSlotSetting";

export type AppConfig = {
  data_path: string | null;
  last_folder: string | null;
  last_theme: number | null;
  guide_volume: number | null;
  fullscreen: boolean | null;
  dark_mode: boolean | null;
  mic_active: boolean | null;
  mic_mirroring: boolean | null;
  preferred_mic: string | null;
  preferred_mic_channel: number | null;
  whisper_model: string | null;
  beam_size: number | null;
  batch_size: number | null;
  last_video_flavor: number | null;
  separator: string | null;
  language_overrides: { [key in string]: string } | null;
  audio_output_vocals: string | null;
  audio_output_instrumental: string | null;
  enable_channel_routing: boolean | null;
  vocals_device_name: string | null;
  vocals_start_channel: number | null;
  instrumental_device_name: string | null;
  instrumental_start_channel: number | null;
  mic_slot_count: number | null;
  mic_slots: Array<MicSlotSetting> | null;
  openai_api_key: string | null;
};
