// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FolderTreeNode = {
  name: string;
  path: string;
  song_count: number;
  total_song_count: number;
  children: Array<FolderTreeNode>;
};
