// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LibraryMenuFilters = {
  artist: string | null;
  album: string | null;
  query: string | null;
};
