// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryMenuFilters } from "./LibraryMenuFilters";

export type LoadSongsParams = {
  search: string | null;
  filters: LibraryMenuFilters;
  skip: number;
  take: number;
};
