// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MetadataFixStatus = {
  total: number;
  processed: number;
  errors: number;
  running: boolean;
};
