// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MetadataCorrection = {
  id: number;
  file_hash: string;
  file_path: string;
  original_title: string;
  original_artist: string;
  original_album: string;
  suggested_title: string;
  suggested_artist: string;
  suggested_album: string;
  suggested_album_art_url: string | null;
  confirmed: boolean;
  applied_to_file: boolean;
  rejected: boolean;
};
