// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MicCaptureOptions } from "./MicCaptureOptions";

export type MicSlotConfig = {
  slot: number;
  device_name: string | null;
  input_channel: number | null;
  options: MicCaptureOptions;
};
