// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MicSlotSetting = {
  device_name: string | null;
  input_channel: number | null;
  enabled: boolean;
};
