// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptSource } from "./TranscriptSource";

export type Song = {
  path: string;
  file_hash: string;
  title: string;
  artist: string;
  album: string;
  duration_secs: number;
  album_art_path: string | null;
  is_analyzed: boolean;
  language: string | null;
  language_confidence: number | null;
  transcript_source: TranscriptSource | null;
  key: string | null;
  override_key: string | null;
  bpm: number | null;
  tempo: number;
  key_offset: number;
  has_multi_singer_stems: boolean;
  is_video: boolean;
};
