// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Song = {
  path: string;
  file_hash: string;
  title: string;
  artist: string;
  album: string;
  duration_secs: number;
  album_art_path: string | null;
  is_analyzed: boolean;
  language: string | null;
  is_video: boolean;
};
