import { invoke } from "@tauri-apps/api/core";

// TODO: These types should be auto-generated by ts-rs
// They match the Rust types in client/src-tauri/src/youtube.rs
export interface YouTubeSearchResult {
  id: string;
  title: string;
  uploader: string;
  duration: number;
  thumbnail: string;
  url: string;
}

export interface YouTubeDownloadResult {
  filepath: string;
  title: string;
  uploader: string;
  duration: number;
  is_audio_only: boolean;
}

export const searchYouTube = async (
  query: string,
  maxResults?: number,
): Promise<YouTubeSearchResult[]> => {
  return await invoke<YouTubeSearchResult[]>("search_youtube", {
    query,
    maxResults,
  });
};

export const downloadYouTubeVideo = async (
  url: string,
  audioOnly: boolean,
): Promise<YouTubeDownloadResult> => {
  return await invoke<YouTubeDownloadResult>("download_youtube_video", {
    url,
    audioOnly,
  });
};

export const getYouTubeVideoInfo = async (url: string) => {
  return await invoke("get_youtube_video_info", { url });
};
